# input2
initial_cohort_file <<- "./input1/init_cohort.csv"
entering_chort_file <<- "./input1/entering_cohort.csv"
oud_trans_file <<- "./shared_data/oud_trans.csv"
block_trans_file <<- "./shared_data/block_trans.csv"
block_init_effect_file <<- "./shared_data/block_init_effect.csv"
all_type_overdose_file <<- "./input1/all_types_overdose.csv"
fatal_overdose_file <<- "./input1/fatal_overdose.csv"
background_mortality_file <<- "./input1/background_mortality.csv"
SMR_file <<- "./input1/SMR.csv"
healthcare_utilization_cost_file <<- "./shared_data/cost_life/healthcare_utilization_cost.csv"
overdose_cost_file <<- "./shared_data/cost_life/overdose_cost.csv"
treatment_utilization_cost_file <<- "./shared_data/cost_life/treatment_utilization_cost.csv"
pharmaceutical_cost_file <<- "./shared_data/cost_life/pharmaceutical_cost.csv"
background_utility_file <<- "./shared_data/cost_life/bg_utility.csv"
oud_utility_file <<- "./shared_data/cost_life/oud_utility.csv"
setting_utility_file <<- "./shared_data/cost_life/setting_utility.csv"
